/** Instrument icons presented in admin icon dialog (paths under /images). */
export const ICON_DIALOG_SRCS = [
  '/images/instruments/accordion.svg',
  '/images/instruments/acoustic-guitar.svg',
  '/images/instruments/audio-cable.svg',
  '/images/instruments/banjo.svg',
  '/images/instruments/bass-guitar.svg',
  '/images/instruments/cassette-tape.svg',
  '/images/instruments/conga.svg',
  '/images/instruments/cymbals.svg',
  '/images/instruments/electric-guitar.svg',
  '/images/instruments/flute.svg',
  '/images/instruments/goblet-drum.svg',
  '/images/instruments/guitar-pick.svg',
  '/images/instruments/harp.svg',
  '/images/instruments/loudspeaker.svg',
  '/images/instruments/lyre.svg',
  '/images/instruments/mandolin.svg',
  '/images/instruments/maraca.svg',
  '/images/instruments/metronome.svg',
  '/images/instruments/microphone_01.svg',
  '/images/instruments/microphone.svg',
  '/images/instruments/note_01.svg',
  '/images/instruments/note.svg',
  '/images/instruments/pan-flute.svg',
  '/images/instruments/piano.svg',
  '/images/instruments/reel-to-reel-tape-recorder.svg',
  '/images/instruments/saxophone.svg',
  '/images/instruments/snare-drum.svg',
  '/images/instruments/synthesizer.svg',
  '/images/instruments/tambourine_01.svg',
  '/images/instruments/tambourine.svg',
  '/images/instruments/treble-clef.svg',
  '/images/instruments/triangle.svg',
  '/images/instruments/trombone.svg',
  '/images/instruments/trumpet.svg',
  '/images/instruments/tuba.svg',
  '/images/instruments/vibraphone.svg',
  '/images/instruments/vinyl-record.svg',
  '/images/instruments/violin.svg',
  '/images/instruments/xylophone.svg',
  '/images/instruments/headset.svg',
] as const

export const BLANK_ICON_SRC =
  "data:image/svg+xml;charset=utf8,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%3E%3C/svg%3E"
